spring:
  application:
    name: qs-inner-web
server:
  port: 881
  context-path: /qs-inner-web

eureka:
  client:
    service-url:
      defaultZone:
    decoder-name: JacksonJson
    prefer-same-zone-eureka: true
    use-dns-for-fetching-service-urls: false
    registry-fetch-interval-seconds: 1
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    metadata-map:
      version:  '@project.version@'
ribbon:
  ServerListRefreshInterval: 1000